### ISSUE TITLE
Add certificate login

### ISSUE THREAD

**Issue by zvg** [oxfs/oxfs#7]
The server is for security,
If the server disables password access

**Comment by RainMark** [comment]
- you can put your public key to server `${USER}/.ssh/authorized_keys`
- the client `~/.ssh/id_rsa.pub` is used to authority firstly.

**Comment by RainMark** [comment]
- you need to set a cert file from command line, like ssh -i /path/xxx.cert right?

**Comment by zvg** [comment]
Yes.

My certificate file name is not the default.

**Comment by mjgardner** [comment]
I’m not a Pythonista but it looks like you want to use the `pkey` or `key_filename` parameter to [Client.connect](https://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient.connect) in Paramiko.

This is also critical for me. I’m using keys rather than certificates but they’re still not named "id_rsa", "id_dsa" or "id_ecdsa". Further, I have enough keys such that if a client asks ssh-agent to cycle through all of them in sequence, chances are the server will disconnect me after too many login attempts before it reaches the right key.

Ideally, you would support the standard [OpenSSH ~/.ssh/config file](https://man.openbsd.org/ssh_config), which has a rich syntax for specifying all kinds of connection parameters per host or pattern. It looks like [Paramiko provides a parser for a limited subset of that syntax](https://docs.paramiko.org/en/stable/api/config.html) that unfortunately does not include directives like [CertificateFile](https://man.openbsd.org/ssh_config#CertificateFile), [IdentityFile](https://man.openbsd.org/ssh_config#IdentityFile), or [IdentitiesOnly](https://man.openbsd.org/ssh_config#IdentitiesOnly). It's that last one that tells OpenSSH to only present specific identities rather than everything ssh-agent has loaded.

I'd also be wary of how you're currently handling passwords when identities *aren't* managed by ssh-agent. It appears you're spawning a new process with a `--password` parameter either as plain or easily-decoded base64 text, which can be read by any other process by that user or root on the same machine. I can't think of any acceptable reason why a user would risk publicly providing their passphrase for a private SSH key that might access any remote system that's authorized the corresponding public key.

**Comment by RainMark** [comment]
> I’m not a Pythonista but it looks like you want to use the `pkey` or `key_filename` parameter to [Client.connect](https://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient.connect) in Paramiko.
> 
> This is also critical for me. I’m using keys rather than certificates but they’re still not named "id_rsa", "id_dsa" or "id_ecdsa". Further, I have enough keys such that if a client asks ssh-agent to cycle through all of them in sequence, chances are the server will disconnect me after too many login attempts before it reaches the right key.
> 
> Ideally, you would support the standard [OpenSSH ~/.ssh/config file](https://man.openbsd.org/ssh_config), which has a rich syntax for specifying all kinds of connection parameters per host or pattern. It looks like [Paramiko provides a parser for a limited subset of that syntax](https://docs.paramiko.org/en/stable/api/config.html) that unfortunately does not include directives like [CertificateFile](https://man.openbsd.org/ssh_config#CertificateFile), [IdentityFile](https://man.openbsd.org/ssh_config#IdentityFile), or [IdentitiesOnly](https://man.openbsd.org/ssh_config#IdentitiesOnly). It's that last one that tells OpenSSH to only present specific identities rather than everything ssh-agent has loaded.

could you like to submit a pull request to support it? I'm little busy currently.

> I'd also be wary of how you're currently handling passwords when identities _aren't_ managed by ssh-agent. It appears you're spawning a new process with a `--password` parameter either as plain or easily-decoded base64 text, which can be read by any other process by that user or root on the same machine. I can't think of any acceptable reason why a user would risk publicly providing their passphrase for a private SSH key that might access any remote system that's authorized the corresponding public key.

yes, it is ugly way. we need find a easy ways to pass the password to the new background thread.
